---
- name: Verificar si el tema GTK ya está instalado
  stat:
    path: "{{ lookup('env', 'HOME') }}/.themes/MacTahoe-Dark"
  register: theme_installed
  become: false

- name: Verificar si el tema libadwaita ya está instalado
  stat:
    path: "{{ lookup('env', 'HOME') }}/.config/gtk-4.0/gtk.css"
  register: libadwaita_installed
  become: false

- name: Verificar si los iconos ya están instalados
  stat:
    path: "{{ lookup('env', 'HOME') }}/.icons/MacTahoe-Dark"
  register: icons_installed
  become: false

- name: Verificar si el cursor ya está instalado
  stat:
    path: "{{ lookup('env', 'HOME') }}/.icons/MacTahoe-cursors"
  register: cursor_installed
  become: false

- name: Clonar MacTahoe-gtk-theme
  become: false
  git:
    repo: https://github.com/vinceliuice/MacTahoe-gtk-theme.git
    dest: /tmp/MacTahoe-gtk-theme
    depth: 1
  when: not theme_installed.stat.exists or not libadwaita_installed.stat.exists

- name: Instalar tema GTK (dark, con bordes)
  become: false
  command: ./install.sh -c dark -b
  args:
    chdir: /tmp/MacTahoe-gtk-theme
  when: not theme_installed.stat.exists

- name: Instalar tema GTK libadwaita (dark, con bordes)
  become: false
  command: ./install.sh -l -b -c dark
  args:
    chdir: /tmp/MacTahoe-gtk-theme
  when: not libadwaita_installed.stat.exists

- name: Clonar MacTahoe-icon-theme (iconos + cursores)
  become: false
  git:
    repo: https://github.com/vinceliuice/MacTahoe-icon-theme.git
    dest: /tmp/MacTahoe-icon-theme
    depth: 1
  when: not icons_installed.stat.exists or not cursor_installed.stat.exists

- name: Instalar iconos
  become: false
  command: ./install.sh -c dark -b
  args:
    chdir: /tmp/MacTahoe-icon-theme
  when: not icons_installed.stat.exists

- name: Instalar cursores
  become: false
  command: ./install.sh
  args:
    chdir: /tmp/MacTahoe-icon-theme/cursors
  when: not cursor_installed.stat.exists

- name: Aplicar tweak de GDM theme (dark)
  become: true
  command: ./tweaks.sh -g -c Dark
  args:
    chdir: /tmp/MacTahoe-gtk-theme
  when: not theme_installed.stat.exists

- name: Permitir tema GTK en apps Flatpak (GTK3)
  become: true
  command: flatpak override --filesystem=xdg-config/gtk-3.0
  when: not theme_installed.stat.exists

- name: Permitir tema GTK en apps Flatpak (GTK4)
  become: true
  command: flatpak override --filesystem=xdg-config/gtk-4.0
  when: not theme_installed.stat.exists

- name: Aplicar tweak de Flatpak (dark)
  become: false
  command: ./tweaks.sh -F -c dark
  args:
    chdir: /tmp/MacTahoe-gtk-theme
  when: not theme_installed.stat.exists
