---
gnome_extensions:
  - appindicatorsupport@rgcjonas.gmail.com
  - blur-my-shell@aunetx
  - user-theme@gnome-shell-extensions.gcampax.github.com
  - dash-to-dock@micxgx.gmail.com
  - copyous@boerdereinar.dev
  - logomenu@aryan_k
  - CoverflowAltTab@palatis.blogspot.com
  - caffeine@patapon.info
  - emoji-copy@felipeftn
  - color-picker@tuberry
  - pip-on-top@rafostar.github.com
  - burn-my-windows@schneegans.github.com
  - just-perfection-desktop@just-perfection
  - globalmenu@ShiroOSL.github.io
