---
- name: Actualizar base de datos de pacman
  pacman:
    update_cache: true

- name: Instalar paquetes de repos oficiales
  pacman:
    name: "{{ pacman_packages }}"
    state: present

- name: Instalar paquetes de AUR
  become: false
  command: paru --pacman /usr/bin/pacman -S --noconfirm --needed {{ aur_packages | join(' ') }}
  register: aur_install
  changed_when: "'there is nothing to do' not in ((aur_install.stdout ~ aur_install.stderr) | lower)"
  when: aur_packages | length > 0

- name: Añadir repositorio Flathub
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: system
  when: flatpak_packages is defined and flatpak_packages | length > 0

- name: Añadir repositorio Gnome nightly
  community.general.flatpak_remote:
    name: gnome-nightly
    state: present
    flatpakrepo_url: https://nightly.gnome.org/gnome-nightly.flatpakrepo
    method: system
  when: gnome_nightly_packages is defined and gnome_nightly_packages | length > 0

- name: Instalar paquetes Flatpak
  community.general.flatpak:
    name: "{{ flatpak_packages }}"
    state: present
    remote: flathub
    method: system
  when: flatpak_packages is defined and flatpak_packages | length > 0
