---
- name: Inicializar toolchain de Rust (stable)
  become: false
  command: rustup default stable
  args:
    creates: "{{ lookup('env', 'HOME') }}/.rustup/toolchains"

- name: Instalar oh-my-pi (pi-coding-agent) vía Bun
  become: false
  command: bun install -g @oh-my-pi/pi-coding-agent
  args:
    creates: "{{ lookup('env', 'HOME') }}/.bun/install/global/node_modules/@oh-my-pi"

- name: Instalar fnm vía Cargo
  become: false
  command: cargo install fnm
  environment:
    PATH: "{{ lookup('env', 'HOME') }}/.cargo/bin:{{ ansible_env.PATH }}"
  args:
    creates: "{{ lookup('env', 'HOME') }}/.cargo/bin/fnm"

- name: Instalar SDKMAN
  become: false
  shell: curl -s "https://get.sdkman.io?rcupdate=false" | zsh
  args:
    creates: "{{ lookup('env', 'HOME') }}/.sdkman/bin/sdkman-init.sh"
