---
- name: Instalar chezmoi
  shell: sh -c "$(curl -fsLS get.chezmoi.io)" -- -b ~/.local/bin
  args:
    creates: "$HOME/.local/bin/chezmoi"
  become: false

- name: Init y apply de dotfiles
  command: >
    ~/.local/bin/chezmoi init --apply
    https://codeberg.org/danicpr/dotfiles.git
  become: false
  environment:
    BW_SESSION: "{{ bw_session }}"
