---
pacman_packages:
  # Base del sistema
  - base-devel
  - git
  - curl
  - zsh
  - zip
  - paru
  - python-pipx
  - rsync

  # Terminal y shell
  - ghostty
  - starship
  - fastfetch
  - neovim
  - fzf
  - zoxide
  - ripgrep
  - unrar
  - unzip

  # Editor
  - zed

  # Desarrollo
  - rustup
  - bun
  - ttf-jetbrains-mono-nerd

  # Aplicaciones
  - zen-browser-bin
  - onlyoffice-bin
  - gimp
  - qbittorrent
  - celluloid
  - vesktop
  # Tema MacTahoe
  - extension-manager
  - mission-center
  - flatpak

aur_packages:
  - gnome-rounded-blur

flatpak_packages:
  - com.github.tchx84.Flatseal
  - com.stremio.Stremio
  - io.github.flattool.Warehouse
  - it.mijorus.gearlever
  - org.vinegarhq.Sober
