---
# Paquetes base agnósticos (se instalan en cualquier entorno/WM)
pacman_packages:
  # Base del sistema
  - base-devel
  - git
  - curl
  - zsh
  - zip
  - unzip
  - unrar
  - paru
  - python-pipx
  - rsync
  - flatpak
  - shelly-flatpak-backend
  # Terminal y shell
  - oh-my-zsh-git
  - zsh-completions
  - zsh-history-substring-search
  - zsh-syntax-highlighting
  - zsh-autosuggestions
  - powerline-fonts
  - ghostty
  - starship
  - fastfetch
  - neovim
  - fzf
  - zoxide
  - ripgrep
  - wl-clipboard
  # Fuentes
  - ttf-jetbrains-mono-nerd
  - ttf-meslo-nerd
  - noto-fonts
  - noto-fonts-cjk
  - noto-fonts-emoji

  # Editor
  - zed

  # Desarrollo
  - rustup
  - bun
  - uv
  - docker
  - github-cli
  - rclone
  # Aplicaciones 
  - zen-browser-bin
  - onlyoffice-bin
  - gimp
  - qbittorrent
  - loupe
  - celluloid
  - vesktop
aur_packages: []

flatpak_packages:
  - org.bluesabre.MenuLibre
  - org.gnome.gitlab.somas.Apostrophe
  - com.github.tchx84.Flatseal
  - com.stremio.Stremio
  - io.github.flattool.Warehouse
  - it.mijorus.gearlever
  - org.vinegarhq.Sober
  - in.cinny.Cinny
# Paquetes específicos de GNOME (solo se instalan si enable_gnome = true)
gnome_pacman_packages:
  - ghostty-nautilus
  - gnome-software
  - extension-manager
  - mission-center

gnome_aur_packages:
  - gnome-rounded-blur

gnome_nightly_packages:
  - org.gnome.NautilusPreviewerDevel

# Drivers y aceleración para GPU Intel (Arc / iGPU)
intel_pacman_packages:
  - intel-compute-runtime
  - intel-media-driver
  - vpl-gpu-rt
  - vulkan-intel
  - lib32-vulkan-intel
  - clinfo
  - libva-utils
