---
pacman_packages:
  # Base del sistema
  - base-devel
  - git
  - curl
  - zsh
  - zip
  - paru
  - python-pipx

  # Terminal y shell
  - ghostty
  - starship
  - fastfetch
  - neovim

  # Editor
  - zed

  # Desarrollo
  - rustup
  - bun
  - ttf-jetbrains-mono-nerd

  # Normal
  - zen-browser-bin

  # Dependencias del tema MacTahoe
  - flatpak

aur_packages:
  - gnome-rounded-blur
