---
- name: Forzar creación de perfil de Zen Browser (headless)
  become: false
  command: timeout 10 zen-browser --headless --first-startup
  args:
    creates: "{{ desktop_home }}/.config/zen/profiles.ini"
  changed_when: false
